"""empty message

Revision ID: 06aadf7db4b4
Revises: 64ad2b17a5f1
Create Date: 2023-05-15 14:04:39.583706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06aadf7db4b4'
down_revision = '64ad2b17a5f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_accomadations', sa.Column('description', sa.String(length=1026), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_accomadations', 'description')
    # ### end Alembic commands ###
