"""empty message

Revision ID: 075418fc5b20
Revises: bf8d77dba2be
Create Date: 2021-09-21 12:33:38.669556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075418fc5b20'
down_revision = 'bf8d77dba2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_rankings',
    sa.Column('ranking_id', sa.Integer(), nullable=False),
    sa.Column('ranking_title', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('ranking_id')
    )
    op.add_column('wg_profiles', sa.Column('ranking', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wg_profiles', 'wg_rankings', ['ranking'], ['ranking_id'])
    op.add_column('wg_users', sa.Column('is_online', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_users', 'is_online')
    op.drop_constraint(None, 'wg_profiles', type_='foreignkey')
    op.drop_column('wg_profiles', 'ranking')
    op.drop_table('wg_rankings')
    # ### end Alembic commands ###
