"""empty message

Revision ID: 08f382e57631
Revises: 2ef65e8dd461
Create Date: 2025-01-23 10:59:01.635059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08f382e57631'
down_revision = '2ef65e8dd461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preepedia', sa.Column('medianum', postgresql.ARRAY(sa.String(length=80)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preepedia', 'medianum')
    # ### end Alembic commands ###
