"""empty message

Revision ID: 13fb2e9f59be
Revises: 2be727874be1
Create Date: 2023-02-21 05:15:36.265630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fb2e9f59be'
down_revision = '2be727874be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_services', sa.Column('time_contingency', sa.String(length=80), nullable=True))
    op.add_column('wg_services', sa.Column('price_contingency', sa.String(length=80), nullable=True))
    op.add_column('wg_services', sa.Column('requirements', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_services', 'requirements')
    op.drop_column('wg_services', 'price_contingency')
    op.drop_column('wg_services', 'time_contingency')
    # ### end Alembic commands ###
