"""empty message

Revision ID: 14b96a47aab0
Revises: 655cd8debe36
Create Date: 2021-11-29 07:43:21.073297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14b96a47aab0'
down_revision = '655cd8debe36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preepedia', sa.Column('has_mainmedia', sa.Boolean(), nullable=True))
    op.add_column('preepedia', sa.Column('captionlist', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('preepedia', sa.Column('has_medialist', sa.Boolean(), nullable=True))
    op.add_column('preepedia', sa.Column('pmcaptionlist', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preepedia', 'pmcaptionlist')
    op.drop_column('preepedia', 'has_medialist')
    op.drop_column('preepedia', 'captionlist')
    op.drop_column('preepedia', 'has_mainmedia')
    # ### end Alembic commands ###
