"""empty message

Revision ID: 1583b4da8561
Revises: db18dfbe84e6
Create Date: 2021-11-26 11:05:01.151835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1583b4da8561'
down_revision = 'db18dfbe84e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_group_pree',
    sa.Column('match_pree', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('pree_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['wg_groups.group_id'], ),
    sa.ForeignKeyConstraint(['pree_id'], ['wg_prees.pree_id'], ),
    sa.PrimaryKeyConstraint('match_pree')
    )
    op.add_column('wg_prees', sa.Column('pree_type', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_prees', 'pree_type')
    op.drop_table('wg_group_pree')
    # ### end Alembic commands ###
