"""empty message

Revision ID: 1b1a4454f3fc
Revises: 4ac1c9ceff5f
Create Date: 2021-12-02 15:32:04.450592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b1a4454f3fc'
down_revision = '4ac1c9ceff5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_subscriptions',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('subscription_name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_table('wg_subscribers',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('is_subscribed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['wg_subscriptions.subscription_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('wg_exclusives',
    sa.Column('exclusive_id', sa.Integer(), nullable=False),
    sa.Column('pree_id', sa.Integer(), nullable=False),
    sa.Column('captionlist', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('playback', sa.String(length=255), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('is_downloadable', sa.Boolean(), nullable=True),
    sa.Column('unlock_requirement', sa.Integer(), nullable=False),
    sa.Column('unlock_fee', sa.Integer(), nullable=True),
    sa.Column('no_of_media', sa.Integer(), nullable=True),
    sa.Column('mediatypes', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('influence', sa.Boolean(), nullable=True),
    sa.Column('stereo', sa.Boolean(), nullable=True),
    sa.Column('md', sa.Boolean(), nullable=True),
    sa.Column('magazine', sa.Boolean(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pree_id'], ['wg_prees.pree_id'], ),
    sa.ForeignKeyConstraint(['unlock_requirement'], ['wg_subscriptions.subscription_id'], ),
    sa.PrimaryKeyConstraint('exclusive_id')
    )
    op.create_table('wg_exclusive_sales',
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('exclusive_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_aquired', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exclusive_id'], ['wg_exclusives.exclusive_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('sale_id')
    )
    op.add_column('wg_prees', sa.Column('is_exclusive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_prees', 'is_exclusive')
    op.drop_table('wg_exclusive_sales')
    op.drop_table('wg_exclusives')
    op.drop_table('wg_subscribers')
    op.drop_table('wg_subscriptions')
    # ### end Alembic commands ###
