"""empty message

Revision ID: 2331579d0296
Revises: e2701eb6bfdd
Create Date: 2021-10-05 20:48:12.492731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2331579d0296'
down_revision = 'e2701eb6bfdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_prees', sa.Column('is_visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_prees', 'is_visible')
    # ### end Alembic commands ###
