"""empty message

Revision ID: 24912a6e78da
Revises: c86015cfa8a5
Create Date: 2023-05-11 12:35:18.233178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24912a6e78da'
down_revision = 'c86015cfa8a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_accomadations', sa.Column('numOfPics', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_accomadations', 'numOfPics')
    # ### end Alembic commands ###
