"""empty message

Revision ID: 257d034e5226
Revises: 5b0af777adb6
Create Date: 2023-03-07 08:36:13.330299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257d034e5226'
down_revision = '5b0af777adb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_votes',
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('choice', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['wg_polls.poll_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('vote_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wg_votes')
    # ### end Alembic commands ###
