"""empty message

Revision ID: 2be727874be1
Revises: 
Create Date: 2023-02-19 12:22:18.845663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be727874be1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_items', sa.Column('pree_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wg_items', 'wg_prees', ['pree_id'], ['pree_id'])
    op.add_column('wg_listings', sa.Column('pree_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wg_listings', 'wg_prees', ['pree_id'], ['pree_id'])
    op.add_column('wg_services', sa.Column('pree_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wg_services', 'wg_prees', ['pree_id'], ['pree_id'])
    op.add_column('wg_vehicles', sa.Column('pree_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wg_vehicles', 'wg_prees', ['pree_id'], ['pree_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wg_vehicles', type_='foreignkey')
    op.drop_column('wg_vehicles', 'pree_id')
    op.drop_constraint(None, 'wg_services', type_='foreignkey')
    op.drop_column('wg_services', 'pree_id')
    op.drop_constraint(None, 'wg_listings', type_='foreignkey')
    op.drop_column('wg_listings', 'pree_id')
    op.drop_constraint(None, 'wg_items', type_='foreignkey')
    op.drop_column('wg_items', 'pree_id')
    # ### end Alembic commands ###
