"""empty message

Revision ID: 2ef65e8dd461
Revises: 06aadf7db4b4
Create Date: 2024-01-19 07:21:19.744520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef65e8dd461'
down_revision = '06aadf7db4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preepedia', sa.Column('state', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preepedia', 'state')
    # ### end Alembic commands ###
