"""empty message

Revision ID: 323ee3d83311
Revises: 6fa4bcba9a92
Create Date: 2023-04-13 08:38:58.017251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323ee3d83311'
down_revision = '6fa4bcba9a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_profiles', sa.Column('displayname', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_profiles', 'displayname')
    # ### end Alembic commands ###
