"""empty message

Revision ID: 3275a45c04be
Revises: 71edf3ca5209
Create Date: 2021-12-09 14:05:02.287947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3275a45c04be'
down_revision = '71edf3ca5209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_exclusives', sa.Column('category', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_exclusives', 'category')
    # ### end Alembic commands ###
