"""empty message

Revision ID: 36279ae65a6e
Revises: 588e7f697b29
Create Date: 2023-03-03 10:59:10.348543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36279ae65a6e'
down_revision = '588e7f697b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_events', sa.Column('venue', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_events', 'venue')
    # ### end Alembic commands ###
