"""empty message

Revision ID: 414fc008f868
Revises: 45834676a157
Create Date: 2023-03-31 23:04:55.598058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414fc008f868'
down_revision = '45834676a157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wg_tokens_omega')
    op.drop_table('wg_tokens_alpha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_tokens_alpha',
    sa.Column('token_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token_val', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('is_assigned', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['wg_users.user_id'], name='wg_tokens_alpha_assigned_to_fkey'),
    sa.PrimaryKeyConstraint('token_id', name='wg_tokens_alpha_pkey')
    )
    op.create_table('wg_tokens_omega',
    sa.Column('token_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token_val', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('is_assigned', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['wg_users.user_id'], name='wg_tokens_omega_assigned_to_fkey'),
    sa.PrimaryKeyConstraint('token_id', name='wg_tokens_omega_pkey')
    )
    # ### end Alembic commands ###
