"""empty message

Revision ID: 44dbb9a9620a
Revises: e97a35702734
Create Date: 2021-12-07 15:15:59.345775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44dbb9a9620a'
down_revision = 'e97a35702734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_exclusives', sa.Column('contingency', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_exclusives', 'contingency')
    # ### end Alembic commands ###
