"""empty message

Revision ID: 45834676a157
Revises: fb8c985c6757
Create Date: 2023-03-31 14:51:34.390982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45834676a157'
down_revision = 'fb8c985c6757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_tokens_alpha',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('token_val', sa.String(length=10), nullable=True),
    sa.Column('is_assigned', sa.Boolean(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('wg_tokens_omega',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('token_val', sa.String(length=10), nullable=True),
    sa.Column('is_assigned', sa.Boolean(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wg_tokens_omega')
    op.drop_table('wg_tokens_alpha')
    # ### end Alembic commands ###
