"""empty message

Revision ID: 4ac1c9ceff5f
Revises: 14b96a47aab0
Create Date: 2021-11-30 13:01:55.363717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ac1c9ceff5f'
down_revision = '14b96a47aab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preepedia', sa.Column('no_of_media', sa.Integer(), nullable=True))
    op.add_column('preepedia', sa.Column('mediatypes', postgresql.ARRAY(sa.String(length=80)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preepedia', 'mediatypes')
    op.drop_column('preepedia', 'no_of_media')
    # ### end Alembic commands ###
