"""empty message

Revision ID: 4e1b09987d0f
Revises: bb36238980a0
Create Date: 2021-09-23 03:55:20.467939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1b09987d0f'
down_revision = 'bb36238980a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('r2')
    op.drop_table('r1')
    op.add_column('wg_profiles', sa.Column('linkages', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_profiles', 'linkages')
    op.create_table('r1',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('r2',
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
