"""empty message

Revision ID: 4f74bca17782
Revises: 257d034e5226
Create Date: 2023-03-10 08:24:05.304707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f74bca17782'
down_revision = '257d034e5226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_classifieds', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_classifieds', 'is_available')
    # ### end Alembic commands ###
