"""empty message

Revision ID: 52de535f10c0
Revises: 323ee3d83311
Create Date: 2023-05-02 07:44:34.442504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52de535f10c0'
down_revision = '323ee3d83311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_listings', sa.Column('interior', postgresql.ARRAY(sa.String(length=80)), nullable=True))
    op.add_column('wg_listings', sa.Column('exterior', postgresql.ARRAY(sa.String(length=80)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_listings', 'exterior')
    op.drop_column('wg_listings', 'interior')
    # ### end Alembic commands ###
