"""empty message

Revision ID: 58b654bebc27
Revises: 97a57d9f69a8
Create Date: 2021-12-14 08:27:30.110318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58b654bebc27'
down_revision = '97a57d9f69a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('lister', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('typeOf', sa.String(length=80), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=80), nullable=True),
    sa.Column('ingredients', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('numOfPics', sa.Integer(), nullable=True),
    sa.Column('dateAdded', sa.DateTime(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lister'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('wg_services',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('lister', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('deliverable', sa.String(length=80), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('timetaken', sa.Integer(), nullable=True),
    sa.Column('timeunit', sa.String(length=80), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('procedures', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('numOfPics', sa.Integer(), nullable=True),
    sa.Column('dateAdded', sa.DateTime(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lister'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.add_column('wg_additional', sa.Column('quantity', sa.Integer(), nullable=True))
    op.drop_column('wg_additional', 'weight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_additional', sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('wg_additional', 'quantity')
    op.drop_table('wg_services')
    op.drop_table('wg_items')
    # ### end Alembic commands ###
