"""empty message

Revision ID: 5b0af777adb6
Revises: e3b1cd460c97
Create Date: 2023-03-07 07:36:02.850781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0af777adb6'
down_revision = 'e3b1cd460c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_polls', sa.Column('category', sa.String(length=40), nullable=True))
    op.add_column('wg_polls', sa.Column('status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_polls', 'status')
    op.drop_column('wg_polls', 'category')
    # ### end Alembic commands ###
