"""empty message

Revision ID: 5c810276aca0
Revises: 36279ae65a6e
Create Date: 2023-03-03 11:17:09.624710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c810276aca0'
down_revision = '36279ae65a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_events', sa.Column('numOfPics', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_events', 'numOfPics')
    # ### end Alembic commands ###
