"""empty message

Revision ID: 619554ff692f
Revises: 46f365165cc4
Create Date: 2021-11-24 08:25:03.735879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '619554ff692f'
down_revision = '46f365165cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('lister', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('condition', sa.String(length=80), nullable=True),
    sa.Column('typeOf', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=80), nullable=True),
    sa.Column('year', sa.String(length=80), nullable=True),
    sa.Column('colors', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('package', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('numOfPics', sa.Integer(), nullable=True),
    sa.Column('dateAdded', sa.DateTime(), nullable=True),
    sa.Column('additional_info', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lister'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('wg_additional',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=255), nullable=True),
    sa.Column('specifications', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('composition', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('other', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['wg_products.product_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wg_additional')
    op.drop_table('wg_products')
    # ### end Alembic commands ###
