"""empty message

Revision ID: 655cd8debe36
Revises: 1583b4da8561
Create Date: 2021-11-27 16:39:05.559844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '655cd8debe36'
down_revision = '1583b4da8561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preepedia',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('drafter', sa.Integer(), nullable=False),
    sa.Column('pagetype', sa.String(length=80), nullable=True),
    sa.Column('section', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('intro', sa.String(length=255), nullable=True),
    sa.Column('subtitles', postgresql.ARRAY(sa.String(length=80)), nullable=True),
    sa.Column('subcontent', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drafter'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_table('biography',
    sa.Column('bio_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('bioname', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['preepedia.page_id'], ),
    sa.PrimaryKeyConstraint('bio_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('biography')
    op.drop_table('preepedia')
    # ### end Alembic commands ###
