"""empty message

Revision ID: 6b6cf5edd324
Revises: ef8192a72dcc
Create Date: 2023-03-19 19:16:03.918059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6cf5edd324'
down_revision = 'ef8192a72dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'wg_followers', 'wg_users', ['figure_id'], ['user_id'])
    op.create_foreign_key(None, 'wg_followers', 'wg_users', ['follower_id'], ['user_id'])
    op.add_column('wg_profiles', sa.Column('figures', sa.Integer(), nullable=True))
    op.add_column('wg_profiles', sa.Column('fraternity', sa.Integer(), nullable=True))
    op.drop_column('wg_profiles', 'following')
    op.drop_column('wg_profiles', 'linkages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_profiles', sa.Column('linkages', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('wg_profiles', sa.Column('following', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('wg_profiles', 'fraternity')
    op.drop_column('wg_profiles', 'figures')
    op.drop_constraint(None, 'wg_followers', type_='foreignkey')
    op.drop_constraint(None, 'wg_followers', type_='foreignkey')
    # ### end Alembic commands ###
