"""empty message

Revision ID: 6fa4bcba9a92
Revises: 7032885acbfe
Create Date: 2023-04-02 10:40:24.673548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa4bcba9a92'
down_revision = '7032885acbfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_tokens_alpha', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    op.add_column('wg_tokens_omega', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_tokens_omega', 'expiry_date')
    op.drop_column('wg_tokens_alpha', 'expiry_date')
    # ### end Alembic commands ###
