"""empty message

Revision ID: 7032885acbfe
Revises: daeecd4855ba
Create Date: 2023-03-31 23:33:04.554847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7032885acbfe'
down_revision = 'daeecd4855ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_tokens_alpha',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('token_val', sa.String(length=7), nullable=True),
    sa.Column('is_assigned', sa.Boolean(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_val')
    )
    op.create_table('wg_tokens_omega',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('token_val', sa.String(length=7), nullable=True),
    sa.Column('is_assigned', sa.Boolean(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_val')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wg_tokens_omega')
    op.drop_table('wg_tokens_alpha')
    # ### end Alembic commands ###
