"""empty message

Revision ID: 71edf3ca5209
Revises: 44dbb9a9620a
Create Date: 2021-12-07 15:23:55.921825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71edf3ca5209'
down_revision = '44dbb9a9620a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_exclusives', sa.Column('currency', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_exclusives', 'currency')
    # ### end Alembic commands ###
