"""empty message

Revision ID: 733a7c2cdc62
Revises: 4e1b09987d0f
Create Date: 2021-09-25 14:49:38.178500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733a7c2cdc62'
down_revision = '4e1b09987d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('message_content', sa.String(length=255), nullable=True),
    sa.Column('sent_date', sa.DateTime(), nullable=True),
    sa.Column('is_seen', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['wg_users.user_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wg_messages')
    # ### end Alembic commands ###
