"""empty message

Revision ID: 77f754ecb9fa
Revises: 2331579d0296
Create Date: 2021-10-07 12:00:53.521850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f754ecb9fa'
down_revision = '2331579d0296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_replies_approvals',
    sa.Column('r_approval_id', sa.Integer(), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_r_approved', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reply_id'], ['wg_comments_replies.reply_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('r_approval_id')
    )
    op.add_column('wg_comments_replies', sa.Column('r_approvals', sa.Integer(), nullable=True))
    op.add_column('wg_comments_replies', sa.Column('r_disapprovals', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_comments_replies', 'r_disapprovals')
    op.drop_column('wg_comments_replies', 'r_approvals')
    op.drop_table('wg_replies_approvals')
    # ### end Alembic commands ###
