"""empty message

Revision ID: 7b0b04315455
Revises: db7d98a24dd1
Create Date: 2021-09-28 13:16:57.257547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b0b04315455'
down_revision = 'db7d98a24dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_prees', sa.Column('comments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_prees', 'comments')
    # ### end Alembic commands ###
