"""empty message

Revision ID: 85e7ef26e847
Revises: 7b0b04315455
Create Date: 2021-10-05 11:05:41.793968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e7ef26e847'
down_revision = '7b0b04315455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_approvals', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.add_column('wg_comments', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.add_column('wg_profiles', sa.Column('date_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_profiles', 'date_added')
    op.drop_column('wg_comments', 'date_added')
    op.drop_column('wg_approvals', 'date_added')
    # ### end Alembic commands ###
