"""empty message

Revision ID: 8b8798c877f7
Revises: ebc2ecb67b54
Create Date: 2021-09-08 22:42:02.832090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8798c877f7'
down_revision = 'ebc2ecb67b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_audits',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('correspondent', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['correspondent'], ['wg_users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('wg_blocks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['wg_users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('wg_followers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('is_following', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['wg_users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('wg_prees',
    sa.Column('pree_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('is_media', sa.Boolean(), nullable=False),
    sa.Column('approvals', sa.Integer(), nullable=True),
    sa.Column('disapprovals', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('pree_id')
    )
    op.create_table('wg_transactions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_of', sa.String(length=80), nullable=True),
    sa.Column('correspondent', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['correspondent'], ['wg_users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('wg_wallets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('wg_approvals',
    sa.Column('pree_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pree_id'], ['wg_prees.pree_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('pree_id')
    )
    op.create_table('wg_media',
    sa.Column('pree_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('no_of_media', sa.Integer(), nullable=True),
    sa.Column('has_image', sa.Boolean(), nullable=True),
    sa.Column('has_audio', sa.Boolean(), nullable=True),
    sa.Column('has_video', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pree_id'], ['wg_prees.pree_id'], ),
    sa.PrimaryKeyConstraint('pree_id')
    )
    op.create_table('wg_quotes',
    sa.Column('pree_id', sa.Integer(), nullable=False),
    sa.Column('the_quote', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pree_id'], ['wg_prees.pree_id'], ),
    sa.PrimaryKeyConstraint('pree_id')
    )
    op.add_column('wg_users', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_users', 'last_login')
    op.drop_table('wg_quotes')
    op.drop_table('wg_media')
    op.drop_table('wg_approvals')
    op.drop_table('wg_wallets')
    op.drop_table('wg_transactions')
    op.drop_table('wg_prees')
    op.drop_table('wg_followers')
    op.drop_table('wg_blocks')
    op.drop_table('wg_audits')
    # ### end Alembic commands ###
