"""added column to exclusives table.

Revision ID: 9425bca73993
Revises: 59e7a4cd9d95
Create Date: 2023-02-10 19:58:36.692349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9425bca73993'
down_revision = '59e7a4cd9d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_exclusives', sa.Column('has_cover_art', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_exclusives', 'has_cover_art')
    # ### end Alembic commands ###
