"""empty message

Revision ID: 9609504d3e31
Revises: bc32beb4bdce
Create Date: 2021-10-25 07:13:44.890710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9609504d3e31'
down_revision = 'bc32beb4bdce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_listings',
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('lister', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('typeOf', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=80), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('baths', sa.Integer(), nullable=True),
    sa.Column('insideSqft', sa.Integer(), nullable=True),
    sa.Column('lotSqft', sa.Integer(), nullable=True),
    sa.Column('parking', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('numOfPics', sa.Integer(), nullable=True),
    sa.Column('dateAdded', sa.DateTime(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lister'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('listing_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wg_listings')
    # ### end Alembic commands ###
