"""empty message

Revision ID: 97a57d9f69a8
Revises: 3275a45c04be
Create Date: 2021-12-11 08:43:08.171423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97a57d9f69a8'
down_revision = '3275a45c04be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_access_types',
    sa.Column('access_id', sa.Integer(), nullable=False),
    sa.Column('access_name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('access_id')
    )
    op.create_table('wg_rankings',
    sa.Column('ranking_id', sa.Integer(), nullable=False),
    sa.Column('ranking_title', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('ranking_id')
    )
    op.create_table('wg_subscriptions',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('subscription_name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_table('wg_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('phonenumber', sa.String(length=80), nullable=True),
    sa.Column('accessType', sa.Integer(), nullable=False),
    sa.Column('dateAdded', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['accessType'], ['wg_access_types.access_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('preepedia',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('drafter', sa.Integer(), nullable=False),
    sa.Column('pagetype', sa.String(length=80), nullable=True),
    sa.Column('section', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('intro', sa.String(length=255), nullable=True),
    sa.Column('subtitles', postgresql.ARRAY(sa.String(length=80)), nullable=True),
    sa.Column('subcontent', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('has_mainmedia', sa.Boolean(), nullable=True),
    sa.Column('no_of_media', sa.Integer(), nullable=True),
    sa.Column('mediatypes', postgresql.ARRAY(sa.String(length=80)), nullable=True),
    sa.Column('captionlist', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('has_medialist', sa.Boolean(), nullable=True),
    sa.Column('pmcaptionlist', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drafter'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_table('wg_audits',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('correspondent', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['correspondent'], ['wg_users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('wg_blocks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['wg_users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('wg_followers',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('is_following', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['wg_users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('wg_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('has_dp', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('dateAdded', sa.DateTime(), nullable=True),
    sa.Column('members', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('wg_listings',
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('lister', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('typeOf', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=80), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('baths', sa.Integer(), nullable=True),
    sa.Column('insideSqft', sa.Integer(), nullable=True),
    sa.Column('lotSqft', sa.Integer(), nullable=True),
    sa.Column('parking', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('numOfPics', sa.Integer(), nullable=True),
    sa.Column('dateAdded', sa.DateTime(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lister'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_table('wg_messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('message_content', sa.String(length=255), nullable=True),
    sa.Column('sent_date', sa.DateTime(), nullable=True),
    sa.Column('is_seen', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['wg_users.user_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('wg_prees',
    sa.Column('pree_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('is_media', sa.Boolean(), nullable=False),
    sa.Column('pree_type', sa.String(length=80), nullable=True),
    sa.Column('approvals', sa.Integer(), nullable=True),
    sa.Column('disapprovals', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('pree_id')
    )
    op.create_table('wg_products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('lister', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('condition', sa.String(length=80), nullable=True),
    sa.Column('typeOf', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=80), nullable=True),
    sa.Column('year', sa.String(length=80), nullable=True),
    sa.Column('colors', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('package', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('numOfPics', sa.Integer(), nullable=True),
    sa.Column('dateAdded', sa.DateTime(), nullable=True),
    sa.Column('additional_info', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lister'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('wg_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('tagline', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('linkages', sa.Integer(), nullable=True),
    sa.Column('groups', sa.Integer(), nullable=True),
    sa.Column('family', sa.Integer(), nullable=True),
    sa.Column('closest', sa.Integer(), nullable=True),
    sa.Column('has_dp', sa.Boolean(), nullable=True),
    sa.Column('has_cv', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['closest'], ['wg_users.user_id'], ),
    sa.ForeignKeyConstraint(['ranking'], ['wg_rankings.ranking_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('wg_subscribers',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('is_subscribed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['wg_subscriptions.subscription_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('wg_transactions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_of', sa.String(length=80), nullable=True),
    sa.Column('correspondent', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['correspondent'], ['wg_users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('wg_vehicles',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('lister', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('condition', sa.String(length=80), nullable=True),
    sa.Column('typeOf', sa.String(length=80), nullable=True),
    sa.Column('fuel', sa.String(length=80), nullable=True),
    sa.Column('transmission', sa.String(length=80), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=80), nullable=True),
    sa.Column('engine', sa.Float(), nullable=True),
    sa.Column('year', sa.String(length=80), nullable=True),
    sa.Column('steering', sa.String(length=80), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('ignition', sa.String(length=80), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('numOfPics', sa.Integer(), nullable=True),
    sa.Column('dateAdded', sa.DateTime(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lister'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_table('wg_wallets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('biography',
    sa.Column('bio_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('bioname', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['preepedia.page_id'], ),
    sa.PrimaryKeyConstraint('bio_id')
    )
    op.create_table('wg_additional',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=255), nullable=True),
    sa.Column('specifications', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('composition', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('other', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['wg_products.product_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('wg_approvals',
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('pree_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pree_id'], ['wg_prees.pree_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_table('wg_comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('pree_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(length=255), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('c_approvals', sa.Integer(), nullable=True),
    sa.Column('c_disapprovals', sa.Integer(), nullable=True),
    sa.Column('replies', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pree_id'], ['wg_prees.pree_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('wg_exclusives',
    sa.Column('exclusive_id', sa.Integer(), nullable=False),
    sa.Column('pree_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('artistname', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('genre', sa.String(length=80), nullable=True),
    sa.Column('features', postgresql.ARRAY(sa.String(length=80)), nullable=True),
    sa.Column('captionlist', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('playback', sa.String(length=255), nullable=True),
    sa.Column('contingency', sa.String(length=255), nullable=True),
    sa.Column('options', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('is_downloadable', sa.Boolean(), nullable=True),
    sa.Column('unlock_requirement', sa.Integer(), nullable=False),
    sa.Column('unlock_fee', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('no_of_media', sa.Integer(), nullable=True),
    sa.Column('mediatypes', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('influence', sa.Boolean(), nullable=True),
    sa.Column('stereo', sa.Boolean(), nullable=True),
    sa.Column('md', sa.Boolean(), nullable=True),
    sa.Column('magazine', sa.Boolean(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pree_id'], ['wg_prees.pree_id'], ),
    sa.ForeignKeyConstraint(['unlock_requirement'], ['wg_subscriptions.subscription_id'], ),
    sa.PrimaryKeyConstraint('exclusive_id')
    )
    op.create_table('wg_group_pree',
    sa.Column('match_pree', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('pree_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['wg_groups.group_id'], ),
    sa.ForeignKeyConstraint(['pree_id'], ['wg_prees.pree_id'], ),
    sa.PrimaryKeyConstraint('match_pree')
    )
    op.create_table('wg_group_relations',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('in_group', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['wg_groups.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('wg_media',
    sa.Column('pree_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('no_of_media', sa.Integer(), nullable=True),
    sa.Column('has_image', sa.Boolean(), nullable=True),
    sa.Column('has_audio', sa.Boolean(), nullable=True),
    sa.Column('has_video', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pree_id'], ['wg_prees.pree_id'], ),
    sa.PrimaryKeyConstraint('pree_id')
    )
    op.create_table('wg_quotes',
    sa.Column('pree_id', sa.Integer(), nullable=False),
    sa.Column('the_quote', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pree_id'], ['wg_prees.pree_id'], ),
    sa.PrimaryKeyConstraint('pree_id')
    )
    op.create_table('wg_comments_approvals',
    sa.Column('c_approval_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_c_approved', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['wg_comments.comment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('c_approval_id')
    )
    op.create_table('wg_comments_replies',
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reply_text', sa.String(length=255), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('r_approvals', sa.Integer(), nullable=True),
    sa.Column('r_disapprovals', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['wg_comments.comment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('reply_id')
    )
    op.create_table('wg_exclusive_sales',
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('exclusive_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_aquired', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exclusive_id'], ['wg_exclusives.exclusive_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('sale_id')
    )
    op.create_table('wg_replies_approvals',
    sa.Column('r_approval_id', sa.Integer(), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_r_approved', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reply_id'], ['wg_comments_replies.reply_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('r_approval_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wg_replies_approvals')
    op.drop_table('wg_exclusive_sales')
    op.drop_table('wg_comments_replies')
    op.drop_table('wg_comments_approvals')
    op.drop_table('wg_quotes')
    op.drop_table('wg_media')
    op.drop_table('wg_group_relations')
    op.drop_table('wg_group_pree')
    op.drop_table('wg_exclusives')
    op.drop_table('wg_comments')
    op.drop_table('wg_approvals')
    op.drop_table('wg_additional')
    op.drop_table('biography')
    op.drop_table('wg_wallets')
    op.drop_table('wg_vehicles')
    op.drop_table('wg_transactions')
    op.drop_table('wg_subscribers')
    op.drop_table('wg_profiles')
    op.drop_table('wg_products')
    op.drop_table('wg_prees')
    op.drop_table('wg_messages')
    op.drop_table('wg_listings')
    op.drop_table('wg_groups')
    op.drop_table('wg_followers')
    op.drop_table('wg_blocks')
    op.drop_table('wg_audits')
    op.drop_table('preepedia')
    op.drop_table('wg_users')
    op.drop_table('wg_subscriptions')
    op.drop_table('wg_rankings')
    op.drop_table('wg_access_types')
    # ### end Alembic commands ###
