"""empty message

Revision ID: a3cfb5065218
Revises: 52de535f10c0
Create Date: 2023-05-11 09:38:21.225132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3cfb5065218'
down_revision = '52de535f10c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_accomadations',
    sa.Column('accomadate_id', sa.Integer(), nullable=False),
    sa.Column('rooms', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('accomadate_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wg_accomadations')
    # ### end Alembic commands ###
