"""empty message

Revision ID: b5113837a437
Revises: 5c810276aca0
Create Date: 2023-03-04 05:05:43.985096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5113837a437'
down_revision = '5c810276aca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_classifieds', sa.Column('contents', postgresql.ARRAY(sa.String(length=10)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_classifieds', 'contents')
    # ### end Alembic commands ###
