"""empty message

Revision ID: bb36238980a0
Revises: 075418fc5b20
Create Date: 2021-09-23 03:04:03.551188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb36238980a0'
down_revision = '075418fc5b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_followers',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('is_following', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['wg_users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wg_followers')
    # ### end Alembic commands ###
