"""empty message

Revision ID: bf8d77dba2be
Revises: cabc0d0ec3dd
Create Date: 2021-09-16 08:50:58.591800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8d77dba2be'
down_revision = 'cabc0d0ec3dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_users', sa.Column('gender', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_users', 'gender')
    # ### end Alembic commands ###
