"""empty message

Revision ID: c86015cfa8a5
Revises: d0d06d7a3050
Create Date: 2023-05-11 11:39:34.374051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c86015cfa8a5'
down_revision = 'd0d06d7a3050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_accomadations', sa.Column('roomslist', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.drop_column('wg_accomadations', 'rooms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_accomadations', sa.Column('rooms', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('wg_accomadations', 'roomslist')
    # ### end Alembic commands ###
