"""empty message

Revision ID: c8cd341880b9
Revises: 85e7ef26e847
Create Date: 2021-10-05 11:56:18.136804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8cd341880b9'
down_revision = '85e7ef26e847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_comments', sa.Column('is_visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_comments', 'is_visible')
    # ### end Alembic commands ###
