"""empty message

Revision ID: cabc0d0ec3dd
Revises: 82bd0abf7cf6
Create Date: 2021-09-16 00:14:46.957840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cabc0d0ec3dd'
down_revision = '82bd0abf7cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_profiles', sa.Column('has_dp', sa.Boolean(), nullable=True))
    op.add_column('wg_profiles', sa.Column('has_cv', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_profiles', 'has_cv')
    op.drop_column('wg_profiles', 'has_dp')
    # ### end Alembic commands ###
