"""empty message

Revision ID: ce0fa9f2a2df
Revises: 1b1a4454f3fc
Create Date: 2021-12-05 12:39:35.624064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce0fa9f2a2df'
down_revision = '1b1a4454f3fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_exclusives', sa.Column('options', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.drop_column('wg_prees', 'is_exclusive')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_prees', sa.Column('is_exclusive', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('wg_exclusives', 'options')
    # ### end Alembic commands ###
