"""empty message

Revision ID: d0d06d7a3050
Revises: a3cfb5065218
Create Date: 2023-05-11 11:24:42.839098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0d06d7a3050'
down_revision = 'a3cfb5065218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_accomadations', sa.Column('lister', sa.Integer(), nullable=False))
    op.add_column('wg_accomadations', sa.Column('pree_id', sa.Integer(), nullable=False))
    op.add_column('wg_accomadations', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('wg_accomadations', sa.Column('typeOf', sa.String(length=80), nullable=True))
    op.add_column('wg_accomadations', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('wg_accomadations', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('wg_accomadations', sa.Column('pets', sa.Boolean(), nullable=True))
    op.add_column('wg_accomadations', sa.Column('ammenities', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('wg_accomadations', sa.Column('additional', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('wg_accomadations', sa.Column('cuisine', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('wg_accomadations', sa.Column('minors', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('wg_accomadations', sa.Column('cooperate', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('wg_accomadations', sa.Column('facilities', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('wg_accomadations', sa.Column('attraction', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('wg_accomadations', sa.Column('transit', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('wg_accomadations', sa.Column('establishment', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('wg_accomadations', sa.Column('languages', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('wg_accomadations', sa.Column('overview', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('wg_accomadations', sa.Column('requirements', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('wg_accomadations', sa.Column('fees', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('wg_accomadations', sa.Column('children', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('wg_accomadations', sa.Column('others', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('wg_accomadations', sa.Column('parking', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('wg_accomadations', sa.Column('subtopics', postgresql.ARRAY(sa.PickleType()), nullable=True))
    op.add_column('wg_accomadations', sa.Column('dateAdded', sa.DateTime(), nullable=True))
    op.add_column('wg_accomadations', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.add_column('wg_accomadations', sa.Column('is_visible', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'wg_accomadations', 'wg_users', ['lister'], ['user_id'])
    op.create_foreign_key(None, 'wg_accomadations', 'wg_prees', ['pree_id'], ['pree_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wg_accomadations', type_='foreignkey')
    op.drop_constraint(None, 'wg_accomadations', type_='foreignkey')
    op.drop_column('wg_accomadations', 'is_visible')
    op.drop_column('wg_accomadations', 'is_available')
    op.drop_column('wg_accomadations', 'dateAdded')
    op.drop_column('wg_accomadations', 'subtopics')
    op.drop_column('wg_accomadations', 'parking')
    op.drop_column('wg_accomadations', 'others')
    op.drop_column('wg_accomadations', 'children')
    op.drop_column('wg_accomadations', 'fees')
    op.drop_column('wg_accomadations', 'requirements')
    op.drop_column('wg_accomadations', 'overview')
    op.drop_column('wg_accomadations', 'languages')
    op.drop_column('wg_accomadations', 'establishment')
    op.drop_column('wg_accomadations', 'transit')
    op.drop_column('wg_accomadations', 'attraction')
    op.drop_column('wg_accomadations', 'facilities')
    op.drop_column('wg_accomadations', 'cooperate')
    op.drop_column('wg_accomadations', 'minors')
    op.drop_column('wg_accomadations', 'cuisine')
    op.drop_column('wg_accomadations', 'additional')
    op.drop_column('wg_accomadations', 'ammenities')
    op.drop_column('wg_accomadations', 'pets')
    op.drop_column('wg_accomadations', 'description')
    op.drop_column('wg_accomadations', 'address')
    op.drop_column('wg_accomadations', 'typeOf')
    op.drop_column('wg_accomadations', 'title')
    op.drop_column('wg_accomadations', 'pree_id')
    op.drop_column('wg_accomadations', 'lister')
    # ### end Alembic commands ###
