"""empty message

Revision ID: d6d953e589a8
Revises: 619554ff692f
Create Date: 2021-11-25 13:44:59.104566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d953e589a8'
down_revision = '619554ff692f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('has_dp', sa.Boolean(), nullable=True),
    sa.Column('dateAdded', sa.DateTime(), nullable=True),
    sa.Column('members', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('wg_group_relations',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('in_group', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['wg_groups.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.add_column('wg_profiles', sa.Column('groups', sa.Integer(), nullable=True))
    op.add_column('wg_profiles', sa.Column('family', sa.Integer(), nullable=True))
    op.add_column('wg_profiles', sa.Column('closest', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wg_profiles', 'wg_users', ['closest'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wg_profiles', type_='foreignkey')
    op.drop_column('wg_profiles', 'closest')
    op.drop_column('wg_profiles', 'family')
    op.drop_column('wg_profiles', 'groups')
    op.drop_table('wg_group_relations')
    op.drop_table('wg_groups')
    # ### end Alembic commands ###
