"""empty message

Revision ID: da54e793b9ff
Revises: b5113837a437
Create Date: 2023-03-04 05:59:02.964458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da54e793b9ff'
down_revision = 'b5113837a437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_volunteers',
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('lister', sa.Integer(), nullable=False),
    sa.Column('pree_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('venue', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=2047), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('contributions', postgresql.ARRAY(sa.String(length=80)), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lister'], ['wg_users.user_id'], ),
    sa.ForeignKeyConstraint(['pree_id'], ['wg_prees.pree_id'], ),
    sa.PrimaryKeyConstraint('volunteer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wg_volunteers')
    # ### end Alembic commands ###
