"""empty message

Revision ID: daeecd4855ba
Revises: 73147f014aa8
Create Date: 2023-03-31 23:32:00.269503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daeecd4855ba'
down_revision = '73147f014aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wg_tokens_alpha')
    op.drop_table('wg_tokens_omega')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_tokens_omega',
    sa.Column('token_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token_val', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('is_assigned', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['wg_users.user_id'], name='wg_tokens_omega_assigned_to_fkey'),
    sa.PrimaryKeyConstraint('token_id', name='wg_tokens_omega_pkey'),
    sa.UniqueConstraint('token_val', name='wg_tokens_omega_token_val_key')
    )
    op.create_table('wg_tokens_alpha',
    sa.Column('token_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token_val', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('is_assigned', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['wg_users.user_id'], name='wg_tokens_alpha_assigned_to_fkey'),
    sa.PrimaryKeyConstraint('token_id', name='wg_tokens_alpha_pkey'),
    sa.UniqueConstraint('token_val', name='wg_tokens_alpha_token_val_key')
    )
    # ### end Alembic commands ###
