"""empty message

Revision ID: db18dfbe84e6
Revises: d6d953e589a8
Create Date: 2021-11-25 13:57:01.630966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db18dfbe84e6'
down_revision = 'd6d953e589a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_groups', sa.Column('status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_groups', 'status')
    # ### end Alembic commands ###
