"""empty message

Revision ID: ddb24230b746
Revises: 24912a6e78da
Create Date: 2023-05-11 20:01:50.504611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddb24230b746'
down_revision = '24912a6e78da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_accomadations', sa.Column('amenities', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.drop_column('wg_accomadations', 'ammenities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_accomadations', sa.Column('ammenities', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True))
    op.drop_column('wg_accomadations', 'amenities')
    # ### end Alembic commands ###
