"""empty message

Revision ID: e2701eb6bfdd
Revises: c8cd341880b9
Create Date: 2021-10-05 20:45:14.443815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2701eb6bfdd'
down_revision = 'c8cd341880b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_comments_approvals',
    sa.Column('c_approval_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_c_approved', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['wg_comments.comment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('c_approval_id')
    )
    op.create_table('wg_comments_replies',
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reply_text', sa.String(length=255), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['wg_comments.comment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wg_users.user_id'], ),
    sa.PrimaryKeyConstraint('reply_id')
    )
    op.add_column('wg_comments', sa.Column('c_approvals', sa.Integer(), nullable=True))
    op.add_column('wg_comments', sa.Column('c_disapprovals', sa.Integer(), nullable=True))
    op.add_column('wg_comments', sa.Column('replies', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_comments', 'replies')
    op.drop_column('wg_comments', 'c_disapprovals')
    op.drop_column('wg_comments', 'c_approvals')
    op.drop_table('wg_comments_replies')
    op.drop_table('wg_comments_approvals')
    # ### end Alembic commands ###
