"""empty message

Revision ID: e3b1cd460c97
Revises: da54e793b9ff
Create Date: 2023-03-05 12:25:00.943809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b1cd460c97'
down_revision = 'da54e793b9ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_polls', sa.Column('pree_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wg_polls', 'wg_prees', ['pree_id'], ['pree_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wg_polls', type_='foreignkey')
    op.drop_column('wg_polls', 'pree_id')
    # ### end Alembic commands ###
