"""empty message

Revision ID: e97a35702734
Revises: ce0fa9f2a2df
Create Date: 2021-12-05 16:38:24.788293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e97a35702734'
down_revision = 'ce0fa9f2a2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_exclusives', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('wg_exclusives', sa.Column('artistname', sa.String(length=80), nullable=True))
    op.add_column('wg_exclusives', sa.Column('genre', sa.String(length=80), nullable=True))
    op.add_column('wg_exclusives', sa.Column('features', postgresql.ARRAY(sa.String(length=80)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_exclusives', 'features')
    op.drop_column('wg_exclusives', 'genre')
    op.drop_column('wg_exclusives', 'artistname')
    op.drop_column('wg_exclusives', 'title')
    # ### end Alembic commands ###
