"""Re-created user table

Revision ID: ebc2ecb67b54
Revises: 
Create Date: 2021-09-07 11:39:31.161247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc2ecb67b54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_access_types',
    sa.Column('access_id', sa.Integer(), nullable=False),
    sa.Column('access_name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('access_id')
    )
    op.create_table('wg_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('phonenumber', sa.String(length=80), nullable=True),
    sa.Column('accessType', sa.Integer(), nullable=False),
    sa.Column('dateAdded', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accessType'], ['wg_access_types.access_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wg_users')
    op.drop_table('wg_access_types')
    # ### end Alembic commands ###
