"""empty message

Revision ID: ef8192a72dcc
Revises: 747905966c54
Create Date: 2023-03-19 18:49:32.703509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef8192a72dcc'
down_revision = '747905966c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_followers', sa.Column('figure_id', sa.Integer(), nullable=False))
    op.drop_constraint('wg_followers_user_id_fkey', 'wg_followers', type_='foreignkey')
    op.create_foreign_key(None, 'wg_followers', 'wg_users', ['figure_id'], ['user_id'])
    op.drop_column('wg_followers', 'user_id')
    op.add_column('wg_profiles', sa.Column('figures', sa.Integer(), nullable=True))
    op.add_column('wg_profiles', sa.Column('fraternity', sa.Integer(), nullable=True))
    op.drop_column('wg_profiles', 'following')
    op.drop_column('wg_profiles', 'linkages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_profiles', sa.Column('linkages', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('wg_profiles', sa.Column('following', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('wg_profiles', 'fraternity')
    op.drop_column('wg_profiles', 'figures')
    op.add_column('wg_followers', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'wg_followers', type_='foreignkey')
    op.create_foreign_key('wg_followers_user_id_fkey', 'wg_followers', 'wg_users', ['user_id'], ['user_id'])
    op.drop_column('wg_followers', 'figure_id')
    # ### end Alembic commands ###
