"""empty message

Revision ID: f2a59cdbe8fa
Revises: 13fb2e9f59be
Create Date: 2023-02-21 05:28:02.595106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a59cdbe8fa'
down_revision = '13fb2e9f59be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_services', sa.Column('address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_services', 'address')
    # ### end Alembic commands ###
