"""empty message

Revision ID: fb8c985c6757
Revises: 6b6cf5edd324
Create Date: 2023-03-24 08:38:03.879597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8c985c6757'
down_revision = '6b6cf5edd324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_requests', sa.Column('typeOf', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_requests', 'typeOf')
    # ### end Alembic commands ###
