"""empty message

Revision ID: fd254228a133
Revises: 027676275482
Create Date: 2023-03-02 11:23:48.987891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd254228a133'
down_revision = '027676275482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wg_logistics', sa.Column('status', sa.String(length=80), nullable=True))
    op.add_column('wg_requests', sa.Column('status', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wg_requests', 'status')
    op.drop_column('wg_logistics', 'status')
    # ### end Alembic commands ###
